# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: PR Lint & Gatsby Build

on: [pull_request]

env:
  ANALYTICS_ID: ${{ secrets.ANALYTICS_ID }}
  CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
  CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
  SECRET_FONTS_URL: ${{ secrets.SECRET_FONTS_URL }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.14.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: yarn
      - run: yarn global add gatsby-cli
      - run: yarn lint
      - run: wget -O fonts.zip ${{ secrets.SECRET_FONTS_URL }}; unzip -j fonts.zip -d ./static/fonts/; rm fonts.zip
      - run: gatsby build
